// src/components/ProjectsCarousel.vue
<script setup lang="ts">
import {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
} from "@/components/ui/carousel";
import { projects } from "@/lib/projectsData";
import { Button } from "@/components/ui/button";
</script>

<template>
  <main class="ml-14 mr-14 w-full lg:mx-auto lg:w-10/12">
    <Carousel
      :opts="{
        loop: true,
      }"
    >
      <CarouselContent>
        <CarouselItem class="w-full" v-for="project in projects">
          <div
            class="flex h-full w-full flex-col rounded-xl border-2 border-textBase lg:flex-row"
          >
            <div class="flex flex-col justify-between lg:w-2/6">
              <img
                :src="project.image"
                :alt="project.name"
                class="h-full rounded-se-lg rounded-ss-lg object-cover lg:rounded-es-lg lg:rounded-se-none"
              />
            </div>
            <div
              class="flex h-full flex-col justify-between gap-6 px-4 pb-4 pt-4 lg:w-4/6 lg:pt-8"
            >
              <div class="flex h-full flex-col gap-6 lg:w-3/4">
                <div class="flex flex-col gap-2">
                  <a
                    class="flex items-end hover:underline"
                    :name="project.name"
                    :href="project.link"
                    target="_blank"
                  >
                    <h2 class="text-xl font-bold">
                      {{ project.name }}
                    </h2>
                    <span class="text-lg">
                      {{ project.domain }}
                    </span>
                  </a>
                  <p class="text-base">{{ project.description }}</p>
                  <p class="text-base">{{ project.fullDescription }}</p>
                </div>
                <div class="flex flex-col gap-2">
                  <span class="text-lg"> Features: </span>
                  <ul class="list-inside list-disc pl-2">
                    <li
                      v-for="feature in project.features"
                      :key="feature"
                      class="text-base"
                    >
                      {{ feature }}
                    </li>
                  </ul>
                </div>
              </div>
              <div
                class="flex flex-col items-end justify-between gap-4 lg:flex-row lg:gap-0"
              >
                <div class="flex flex-col gap-2 lg:w-full">
                  <span> Built With </span>
                  <div class="flex flex-wrap gap-2">
                    <img
                      v-for="tech in project.technologies"
                      :src="`https://skillicons.dev/icons?i=${tech}`"
                      :alt="tech"
                      class="h-10 w-10"
                    />
                  </div>
                </div>
                <div class="flex items-center gap-4">
                  <a
                    v-if="project.sourceCode"
                    :href="project.sourceCode"
                    target="_blank"
                    name="GitHub"
                  >
                    <Button class="gap-1 text-base">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        stroke-width="2"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        class="lucide lucide-github h-6 w-6"
                      >
                        <path
                          d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4"
                        />
                        <path d="M9 18c-4.51 2-5-2-7-2" />
                      </svg>
                      <span> Source Code </span>
                    </Button>
                  </a>
                  <a :href="project.link" :name="project.name" target="_blank">
                    <Button class="gap-1 text-base">
                      <span> Visit It </span>
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        stroke-width="2"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        class="lucide lucide-arrow-up-right h-6 w-6"
                      >
                        <path d="M7 7h10v10" />
                        <path d="M7 17 17 7" />
                      </svg>
                    </Button>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </CarouselItem>
      </CarouselContent>
      <CarouselPrevious
        class="border-textBase bg-transparent text-textBase hover:bg-primary"
      />
      <CarouselNext
        class="ml-4 border-textBase bg-transparent text-textBase hover:bg-primary"
      />
    </Carousel>
  </main>
</template>

// src/components/projects-carousel.tsx
import Carousel, {
  Slider,
  SliderContainer,
  ThumsSlider,
} from '@/components/ui/carousel';
import { projects } from '@/lib/projectsData';
import { ShinyButton } from './ui/shiny-button';
import { Github } from 'lucide-react';

export default function ProjectsCarousel() {
  const OPTIONS = { loop: false };
  return (
    <>
      <div className='lg:w-[95%] sm:w-[80%] w-[90%] mx-auto h-full'>
        <Carousel options={OPTIONS} className='relative'>
          <SliderContainer className='gap-2'>
            {projects.map((project) => (
              <Slider
                className='xl:h-[40rem] sm:h-full h-[600px] w-full bg-card/80 rounded-xl flex flex-col sm:flex-row items-center'
                thumnailSrc={project.thumbnail}
                key={project.name}
              >
                <img
                  src={project.image}
                  width={1400}
                  height={800}
                  alt='img'
                  className='h-[200px] sm:h-full object-cover w-full sm:w-[30%] border-b sm:border-b-0 sm:border-r border-accent'
                />
                <div className='flex mx-4 w-full sm:w-[70%] flex-col justify-between h-full py-4 overflow-y-auto'>
                  <div className='flex flex-col gap-4'>
                    <h1 className='text-xl sm:text-2xl font-bold text-card-foreground'>
                      {project.name}
                      <span className='text-xl sm:text-2xl'>
                        {project.domain}
                      </span>
                    </h1>
                    <p className='text-sm sm:text-base text-balance text-secondary-foreground'>
                      {project.description}
                    </p>
                    <ul className='*:list-outside space-y-2'>
                      {project.features.map((feat) => (
                        <li
                          key={feat}
                          className='text-sm sm:text-base text-secondary-foreground rounded-md flex gap-1 items-start'
                        >
                          <svg
                            width="20"
                            height="20"
                            viewBox="0 0 24 24"
                            xmlns="http://www.w3.org/2000/svg"
                            className="flex-shrink-0 mt-1"
                          >
                            <g fill="currentColor">
                              <path d="m14.75 7.784l1.414-1.415l4.242 4.243l-4.242 4.243l-1.415-1.415l2.829-2.828z" />
                              <path d="m10.507 13.44l1.414 1.415l4.243-4.243L11.92 6.37l-1.414 1.415l1.847 1.846h-4.76a4 4 0 0 0-4 4v4h2v-4a2 2 0 0 1 2-2h4.723z" />
                            </g>
                          </svg>
                          <span>{feat}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                  <div className='flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 sm:gap-0 mt-4'>
                    <div className='flex flex-wrap gap-2'>
                      {project.technologies.map((tech) => (
                        <img
                          key={tech}
                          src={`https://skillicons.dev/icons?i=${tech}`}
                          alt={tech}
                          className="h-10 w-10 sm:h-14 sm:w-14"
                        />
                      ))}
                    </div>
                    <div className='flex flex-wrap gap-2 items-center w-full sm:w-auto'>
                      {project.sourceCode && (
                        <a href={project.sourceCode} className="w-full sm:w-auto">
                          <ShinyButton childrenClassName='!flex gap-2 w-full sm:w-auto justify-center'>
                            <Github className='h-5 w-5 sm:h-6 sm:w-6' />
                            <span>Source Code</span>
                          </ShinyButton>
                        </a>
                      )}
                      {project.link && (
                        <a href={project.link} className="w-full sm:w-auto">
                          <ShinyButton className="w-full sm:w-auto">
                            <span>Visit It</span>
                          </ShinyButton>
                        </a>
                      )}
                    </div>
                  </div>
                </div>
              </Slider>
            ))}
          </SliderContainer>
          <ThumsSlider />
        </Carousel>
      </div>
    </>
  );
}
